/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./lipsum.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lipsum.geometry} material={materials.lipsum} position={[0.01, 1.2, -0.74]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/lipsum.gltf')
