/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-6.83, 2.74, 0.5]} rotation={[1.42, 0.03, 1.57]} scale={0.01}>
        <group position={[-68.79, -373.36, 33.05]} rotation={[-0.89, -0.58, -0.26]}>
          <mesh geometry={nodes.Mesh001.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh001_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-106.94, -501.89, 148.12]} rotation={[0.06, -0.43, 0.06]}>
          <mesh geometry={nodes.Mesh010.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh010_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-121.34, -553.63, 173.15]} rotation={[-0.37, -0.2, -0.04]}>
          <mesh geometry={nodes.Mesh013.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh013_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-136.23, -608.61, 189.49]} rotation={[-0.49, -1.15, 0.11]}>
          <mesh geometry={nodes.Mesh016.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh016_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-151.26, -665.28, 197.96]} rotation={[2.01, 0.97, -2.69]}>
          <mesh geometry={nodes.Mesh019.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh019_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-166.12, -722.64, 197.3]} rotation={[-2.8, 1.22, -2.74]}>
          <mesh geometry={nodes.Mesh022.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh022_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-180.59, -779.55, 189.41]} rotation={[0.19, 0.21, -0.35]}>
          <mesh geometry={nodes.Mesh025.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh025_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-194.59, -835.46, 175.56]} rotation={[-2.2, 1.18, -2.96]}>
          <mesh geometry={nodes.Mesh028.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh028_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-80.48, -410.91, 77.39]} rotation={[-0.64, -1.07, -0.6]}>
          <mesh geometry={nodes.Mesh004.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh004_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-93.26, -454.06, 115.96]} rotation={[2.4, -0.66, -2.91]}>
          <mesh geometry={nodes.Mesh007.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh007_1.geometry} material={materials['RS Material_1_1']} />
        </group>
        <group position={[-111.65, -518.61, 157.57]} rotation={[-0.98, -0.09, 0]}>
          <mesh geometry={nodes.Mesh011.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh011_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-126.28, -571.74, 179.37]} rotation={[2.83, -0.27, -2.58]}>
          <mesh geometry={nodes.Mesh014.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh014_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-141.23, -627.31, 193.4]} rotation={[0.02, 0.3, -0.33]}>
          <mesh geometry={nodes.Mesh017.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh017_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-72.58, -385.28, 48.36]} rotation={[2.79, -1.02, -2.21]}>
          <mesh geometry={nodes.Mesh002.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh002_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-156.23, -684.42, 198.31]} rotation={[0.42, -0.5, -0.22]}>
          <mesh geometry={nodes.Mesh020.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh020_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-171.01, -741.73, 195.61]} rotation={[0.07, 1.56, -0.08]}>
          <mesh geometry={nodes.Mesh023.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh023_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-185.34, -798.39, 185.74]} rotation={[-0.28, -0.69, -0.67]}>
          <mesh geometry={nodes.Mesh026.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh026_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-199.07, -853.63, 169.2]} rotation={[-2.9, -1.51, -2.59]}>
          <mesh geometry={nodes.Mesh029.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh029_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-84.66, -424.87, 90.75]} rotation={[0.55, 1.06, -1.21]}>
          <mesh geometry={nodes.Mesh005.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh005_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-97.72, -469.47, 127.5]} rotation={[-0.28, 1.28, -0.91]}>
          <mesh geometry={nodes.Mesh008.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh008_1.geometry} material={materials['RS Material_1']} />
        </group>
        <group position={[-65.16, -362.39, 17]} rotation={[-2.25, -1.32, -0.55]}>
          <mesh geometry={nodes.Mesh.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-116.49, -536.07, 165.5]} rotation={[-1.82, -1.06, -1.78]}>
          <mesh geometry={nodes.Mesh012.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh012_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-131.23, -589.98, 185.13]} rotation={[-2.81, 1.1, 3.09]}>
          <mesh geometry={nodes.Mesh015.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh015_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-146.25, -646.29, 195.78]} rotation={[2.48, 0.6, -2.5]}>
          <mesh geometry={nodes.Mesh018.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh018_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-161.21, -703.55, 198.66]} rotation={[-3.05, -1.16, -2.93]}>
          <mesh geometry={nodes.Mesh021.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh021_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-175.84, -760.71, 193.08]} rotation={[0.65, -0.01, 0.1]}>
          <mesh geometry={nodes.Mesh024.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh024_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-189.98, -816.95, 180.79]} rotation={[3.05, 0.68, -2.66]}>
          <mesh geometry={nodes.Mesh027.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh027_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-76.48, -397.83, 63.11]} rotation={[2.64, -0.14, -2.62]}>
          <mesh geometry={nodes.Mesh003.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh003_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-88.87, -439.03, 103.89]} rotation={[-0.96, -0.42, -0.24]}>
          <mesh geometry={nodes.Mesh006.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh006_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <group position={[-102.28, -485.39, 138.3]} rotation={[-2.18, -0.97, -2.08]}>
          <mesh geometry={nodes.Mesh009.geometry} material={materials['RS Material_1_2']} />
          <mesh geometry={nodes.Mesh009_1.geometry} material={materials['RS Material_1_0']} />
        </group>
        <mesh geometry={nodes.wire.geometry} material={materials['RS Material_1_3']} />
      </group>
      <group position={[-1.05, 1.06, -0.39]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh031.geometry} material={materials.Frame} />
        <mesh geometry={nodes.Mesh031_1.geometry} material={materials['Material #350']} />
        <mesh geometry={nodes.Mesh031_2.geometry} material={materials['Material #25']} />
        <mesh geometry={nodes.Mesh031_3.geometry} material={materials['Material #26']} />
        <mesh geometry={nodes.Group_126.geometry} material={materials['Group 126']} position={[-0.37, 1.74, -0.12]} scale={[63.89, 99.47, 66.45]} />
      </group>
      <group position={[0.48, 1.11, -0.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh033.geometry} material={materials['Frame.002']} />
        <mesh geometry={nodes.Mesh033_1.geometry} material={materials['Material #350.002']} />
        <mesh geometry={nodes.Mesh033_2.geometry} material={materials['Material #25.002']} />
        <mesh geometry={nodes.Mesh033_3.geometry} material={materials['Material #26.002']} />
      </group>
      <group position={[-0.25, 1.08, -0.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh034.geometry} material={materials['Frame.003']} />
        <mesh geometry={nodes.Mesh034_1.geometry} material={materials['Material #350.003']} />
        <mesh geometry={nodes.Mesh034_2.geometry} material={materials['Material #25.003']} />
        <mesh geometry={nodes.Mesh034_3.geometry} material={materials['Material #26.003']} />
        <mesh geometry={nodes['Group_126_(1)'].geometry} material={materials['Group 126 (1)']} position={[-0.07, 1.78, 1.21]} scale={[70.2, 100, 69.67]} />
      </group>
      <group position={[1.19, 1.11, -0.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh032.geometry} material={materials['Frame.004']} />
        <mesh geometry={nodes.Mesh032_1.geometry} material={materials['Material #350.004']} />
        <mesh geometry={nodes.Mesh032_2.geometry} material={materials['Material #25.004']} />
        <mesh geometry={nodes.Mesh032_3.geometry} material={materials['Material #26.004']} />
        <mesh geometry={nodes['topbots-chatbots-4-busuncle-missedbus-opt001'].geometry} material={materials['topbots-chatbots-4-busuncle-missedbus-opt.001']} position={[0.41, 1.76, 0.26]} scale={[77.02, 100, 68.04]} />
      </group>
      <group position={[0.48, 1.86, -0.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh035.geometry} material={materials['Frame.005']} />
        <mesh geometry={nodes.Mesh035_1.geometry} material={materials['Material #350.005']} />
        <mesh geometry={nodes.Mesh035_2.geometry} material={materials['Material #25.005']} />
        <mesh geometry={nodes.Mesh035_3.geometry} material={materials['Material #26.005']} />
      </group>
      <group position={[-0.25, 1.84, -0.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh036.geometry} material={materials['Frame.006']} />
        <mesh geometry={nodes.Mesh036_1.geometry} material={materials['Material #350.006']} />
        <mesh geometry={nodes.Mesh036_2.geometry} material={materials['Material #25.006']} />
        <mesh geometry={nodes.Mesh036_3.geometry} material={materials['Material #26.006']} />
        <mesh geometry={nodes['Screenshot_2022-11-07_033253'].geometry} material={materials['Screenshot 2022-11-07 033253']} position={[-0.42, 1.68, -0.47]} scale={[73.38, 100, 65.27]} />
      </group>
      <group position={[-1.05, 1.8, -0.39]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh037.geometry} material={materials['Frame.007']} />
        <mesh geometry={nodes.Mesh037_1.geometry} material={materials['Material #350.007']} />
        <mesh geometry={nodes.Mesh037_2.geometry} material={materials['Material #25.007']} />
        <mesh geometry={nodes.Mesh037_3.geometry} material={materials['Material #26.007']} />
        <mesh geometry={nodes['Screenshot_2022-11-07_033229'].geometry} material={materials['Screenshot 2022-11-07 033229']} position={[-0.22, 1.7, -0.05]} scale={[67, 100, 66.78]} />
      </group>
      <group position={[1.19, 1.87, -0.4]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh038.geometry} material={materials['Frame.008']} />
        <mesh geometry={nodes.Mesh038_1.geometry} material={materials['Material #350.008']} />
        <mesh geometry={nodes.Mesh038_2.geometry} material={materials['Material #25.008']} />
        <mesh geometry={nodes.Mesh038_3.geometry} material={materials['Material #26.008']} />
      </group>
      <mesh geometry={nodes['Group_126_(3)'].geometry} material={materials['Group 126 (3)']} position={[0.48, 1.84, -0.38]} rotation={[Math.PI / 2, 0, 0]} scale={[0.7, 1, 0.65]} />
      <mesh geometry={nodes['Group_126_(4)'].geometry} material={materials['Group 126 (4)']} position={[0.47, 1.1, -0.38]} rotation={[Math.PI / 2, 0, 0]} scale={[0.69, 1, 0.65]} />
      <mesh geometry={nodes.Group_125.geometry} material={materials['Group 125']} position={[1.19, 1.86, -0.38]} rotation={[Math.PI / 2, 0, 0]} scale={[0.71, 1, 0.64]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
